### PR TITLE
Auto-generate Thumbnails & Preview Images

### PR DESCRIPTION
**Pull request by curran**
This PR adds a service that generates thumbnail and preview images automatically for visualizations.

### CODE REVIEW

**Comment by curran** [comment]
@micahstubbs It may be interesting for you to have a look here!

The strategy is to generate 1 thumbnail every 10 second or so until they are all generated.

**Comment by curran** [comment]
Current status: need to implement gateway for storing images in the database.

**Comment by micahstubbs** [comment]
this is interesting.  I like the 10 sec delay strategy.  curious, what database do you store the images in?

**Comment by curran** [comment]
Well, that's what I'll be implementing next. The rest of VizHub is already using MongoDB, with [ShareDB](https://github.com/share/sharedb) (real-time layer) on top. I think the easiest way forward would be to store the images in the same way, using ShareDB.

**Comment by micahstubbs** [comment]
good to see this one go in 👍

**Comment by curran** [comment]
Super excited to see it land as well. This opens up so many more possibilities!

**Pull request merged**
